# See https://pre-commit.com for more information
---
repos:
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-added-large-files
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          - id: check-symlinks
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
          - id: gitlint
    - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
      rev: 3.0.3
      hooks:
          - id: editorconfig-checker
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.17.0
      hooks:
          - id: pyupgrade
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.3
      hooks:
          - id: ruff
          - id: ruff-format
