import datetime
import logging
import os
import re
import shlex
import shutil
import textwrap
from pathlib import Path
from typing import Literal

from normfn.exceptions import FatalError

logger = logging.getLogger(__name__)

EFFECTIVE_SEP: str = r"\\" if os.sep == "\\" else os.sep

BASENAME_EXCLUDE_PATTERNS: frozenset[re.Pattern[str]] = frozenset(
    {re.compile(r"\..*"), re.compile("Icon\r"), re.compile(r".*\.lo?ck")}
)

FULLNAME_EXCLUDE_PATTERNS: frozenset[re.Pattern[str]] = frozenset(
    {
        re.compile(r".*\.git" + EFFECTIVE_SEP + r".*"),
        re.compile(r".*\.svn" + EFFECTIVE_SEP + r".*"),
        re.compile(r".*\.hg" + EFFECTIVE_SEP + r".*"),
        re.compile(r".*\.bzr" + EFFECTIVE_SEP + r".*"),
    }
)


def should_exclude(filename: str, basename: str) -> tuple[bool, re.Pattern[str] | None]:
    for current_pattern in BASENAME_EXCLUDE_PATTERNS:
        if re.fullmatch(current_pattern, basename):
            return (True, current_pattern)

    for current_pattern in FULLNAME_EXCLUDE_PATTERNS:
        if re.fullmatch(current_pattern, filename):
            return (True, current_pattern)

    return (False, None)


def get_pdf_creation_date(filename: Path) -> datetime.datetime | None:
    if filename.suffix.lower() != ".pdf":
        return None

    try:
        import pypdf  # noqa: PLC0415
    except ImportError:
        logger.info("pypdf library not available; cannot read PDF creation date")
        return None

    result: datetime.datetime | None = None

    try:
        reader = pypdf.PdfReader(str(filename))

        if reader.metadata is None:
            logger.info(f"No metadata found in PDF {filename}")
        else:
            creation_date = reader.metadata.creation_date
            if creation_date is None:
                logger.info(f"No creation date found in PDF metadata for {filename}")
            elif not isinstance(creation_date, datetime.datetime):
                logger.info(
                    "Unexpected type for creation date in PDF %s: %s",
                    filename,
                    type(creation_date),
                )
            elif creation_date.tzinfo is None:
                result = creation_date.replace(tzinfo=datetime.UTC)
            else:
                result = creation_date
    except Exception as e:  # noqa: BLE001
        logger.info(f"Could not read PDF creation date for {filename}: {e}")

    return result


def get_timetouse(
    time_option: Literal["now", "earliest", "latest"], filename: Path
) -> datetime.datetime:
    stat = filename.stat()
    ctime = datetime.datetime.fromtimestamp(stat.st_ctime, tz=datetime.UTC)
    mtime = datetime.datetime.fromtimestamp(stat.st_mtime, tz=datetime.UTC)

    if time_option == "now":
        timetouse = datetime.datetime.now(tz=datetime.UTC)
    elif time_option == "earliest":
        timetouse = min(ctime, mtime)
    else:
        timetouse = max(ctime, mtime)

    return timetouse


def shiftfile(undo_log_file: Path | None, source: Path, target: Path) -> None:
    source = source.resolve()
    target = target.resolve()

    dt_now = datetime.datetime.now(tz=datetime.UTC).strftime("%Y-%m-%dT%H-%M-%S")

    try:
        shutil.move(source, target)
    except PermissionError as permission_error:
        filename: str = permission_error.filename  # pyright: ignore[reportAny]
        if filename == source:
            msg = f"Permission denied on source: {filename}"
            raise FatalError(msg) from permission_error

        if filename == target:
            msg = f"Permission denied on target: {filename}"
            raise FatalError(msg) from permission_error

        raise

    if undo_log_file:
        check_undo_log_file_header(undo_log_file)
        with undo_log_file.open("a", encoding="utf-8") as log_file:
            _ = log_file.write(f"# {dt_now}: moving {source} to {target}\n")
            _ = log_file.write(
                f"mv {shlex.quote(str(target))} {shlex.quote(str(source))}\n"
            )
    logger.info(f"{source} moved to {target}")


def check_undo_log_file_header(undo_log_file: Path) -> None:
    if not undo_log_file.exists():
        undo_log_file.parent.mkdir(parents=True, exist_ok=True)
        with undo_log_file.open("w", encoding="utf-8") as log_file:
            wrapper = textwrap.TextWrapper(initial_indent="# ", subsequent_indent="# ")
            _ = log_file.write("#!/bin/sh\n")
            _ = log_file.write(
                wrapper.fill(
                    "File generated by normfn "
                    + "(see http://www.github.com/andrewferrier/normfn). This file is "
                    + "utf-8 encoded)"
                )
                + "\n"
            )
            _ = log_file.write("#\n")
            _ = log_file.write(
                wrapper.fill(
                    "This file contains shell commands which can be "
                    + "run to invert (undo) the effects of "
                    + "running normfn. They must be run in *reverse order*. "
                    + f"You can achieve this by running `tac {undo_log_file}"
                    + " | sh`. If you wish, you can edit "
                    + "the file first to control which actions are undone."
                )
                + "\n"
            )
            _ = log_file.write("#\n")
            _ = log_file.write(
                wrapper.fill(
                    "(Specific note for MacOS: tac may not be installed. "
                    + "You can install gtac, the "
                    + "equivalent command, using `brew install coreutils`. "
                    + "You will need Homebrew - "
                    + "http://brew.sh/ - installed)"
                )
                + "\n"
            )
            _ = log_file.write("\n")
