---
name: Build Packages
on: [push]

jobs:
  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Install make
        run: pacman -Syu make
      - name: Build Arch package
        run: make buildarch
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ls
        run: ls -Rla
      - name: Build .deb package
        run: make builddeb
