---
name: Build Arch Package
on: [push]

jobs:
  test-run:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Set proper repository url in PKGBUILD
        run: sed -i "s|%URL%|${{ github.server_url }}/${{ github.repository }}|" PKGBUILD_template
      - name: Build Arch Linux package
        uses: FFY00/build-arch-package@v1
        with:
          BUILD_SCRIPT: extra-x86_64-build
          PKGBUILD: $GITHUB_WORKSPACE/PKGBUILD_template
          OUTDIR: $HOME/arch-packages
