---
name: Release Please

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    container:
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Build Debian Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --all # required to make 'git describe' work
          make determineversion
          # gh release upload ${{ steps.release.outputs.tag_name }} *.deb
      - name: Build Arch Linux package
        uses: ./
        with:
          BUILD_SCRIPT: extra-x86_64-build
          PKGBUILD: $GITHUB_WORKSPACE/PKGBUILD
          OUTDIR: $HOME
