---
name: Check conventional commits
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  commit_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: webiny/action-conventional-commits@v1.3.0
