---
name: Release Please

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: normfn
          include-v-in-tag: false
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload Release Artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --all # required to make 'git describe' work
          make builddeb
          #sudo add-apt-repository universe
          #sudo apt update
          #sudo apt install makepkg
          #make buildarch
          gh release upload ${{ steps.release.outputs.tag_name }} *.deb
          #gh release upload ${{ steps.release.outputs.tag_name }} *.zst
