---
name: Update README

on:
  push:
    branches: [master]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get help
        uses: mathiasvr/command-output@v2.0.0
        id: vars
        with:
          run: ./normfn --help
      - name: Update file
        uses: wow-actions/update-file@v1
        with:
          commit_message: 'chore: update README [skip ci]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: README.md
          content: "```\n${{ steps.vars.outputs.stdout }}\n```"
