---
name: Update README
permissions:
  contents: write

on:
  push:
    branches: [master]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install normfn
        run: uv sync
      - name: Get help
        uses: mathiasvr/command-output@v2.0.0
        id: vars
        with:
          run: uv run normfn --help
      - name: Update file
        uses: wow-actions/update-file@v1
        with:
          commit_message: 'chore: update README [skip ci]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: README.md
          content: "```\n${{ steps.vars.outputs.stdout }}\n```"
